### ISSUE TITLE
Feature request: undress this package to a universal ros_teleop_mobile_web package

### ISSUE THREAD

**Issue by Timple** [tue-robotics/tue_mobile_ui#13]
The teleop part of this package is very nice.

Maybe separate this from the whole shebang and release it as standalone?

Let me know the thoughts and how difficult it might be. I might get started on it myself.

**Comment by reinzor** [comment]
It is actually a separate angular js directive; should be relatively straight forward ..

**Comment by Timple** [comment]
https://github.com/tue-robotics/teleop_twist_web
