### ISSUE TITLE
DEMO UI

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_mobile_ui#16]
Current status:

Challenge open GUI is integrated (at least the HTML, Styling and the JS). For some reason, I am not receiving any images. Could you take a look at this @Rayman.

<img width="1642" alt="screen shot 2017-10-03 at 22 32 29" src="https://user-images.githubusercontent.com/4176023/31147733-12e86212-a88b-11e7-92ef-09173d234b59.png">

<img width="1645" alt="screen shot 2017-10-03 at 22 32 22" src="https://user-images.githubusercontent.com/4176023/31147734-13034cf8-a88b-11e7-8159-ec8237f3405c.png">

I think the framework for adding all the functionalities is there. Things that are missing:

- For some reason not getting an image from the head
- Somebody is throwing exception on the console (check debugger)
- Implement body pose functionality
- Not sure whether teleop canvas work properly on tablet, maybe use hammer js for this
- Implement tts with log 

GL on Saturday =D

**Comment by reinzor** [comment]
@jlunenburg , current status

**Comment by jlunenburg** [comment]
This is mentioned in other issues
