### ISSUE TITLE
warning in amigo-start between rosbridge_websocket and text_to_speech

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/tue_mobile_ui#19]
I get a lot of warnings in the amigo-start.
I used the speech interface to type text and it works but this warning here is annoying.

[WARN] [1509792177.366028]: Could not process inbound connection: [/amigo/rosbridge_websocket] is not a publisher of [/amigo/text_to_speech/input]. Topics are [['/rosout', 'rosgraph_msgs/Log']]{'message_definition': 'string data\n', 'callerid': '/amigo/rosbridge_websocket', 'tcp_nodelay': '0', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'topic': '/amigo/text_to_speech/input', 'type': 'std_msgs/String'}
[WARN] [1509792177.366631]: Could not process inbound connection: [/amigo/rosbridge_websocket] is not a publisher of [/amigo/text_to_speech/input]. Topics are [['/rosout', 'rosgraph_msgs/Log']]{'message_definition': 'string data\n', 'callerid': '/amigo/text_to_speech', 'tcp_nodelay': '0', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'topic': '/amigo/text_to_speech/input', 'type': 'std_msgs/String'}
[WARN] [1509792178.368430]: Could not process inbound connection: [/amigo/rosbridge_websocket] is not a publisher of [/amigo/text_to_speech/input]. Topics are [['/rosout', 'rosgraph_msgs/Log']]{'message_definition': 'string data\n', 'callerid': '/amigo/text_to_speech', 'tcp_nodelay': '0', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'topic': '/amigo/text_to_speech/input', 'type': 'std_msgs/String'}
[WARN] [1509792180.369414]: Could not process inbound connection: [/amigo/rosbridge_websocket] is not a publisher of [/amigo/text_to_speech/input]. Topics are [['/rosout', 'rosgraph_msgs/Log']]{'message_definition': 'string data\n', 'callerid': '/amigo/text_to_speech', 'tcp_nodelay': '0', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'topic': '/amigo/text_to_speech/input', 'type': 'std_msgs/String'}
[WARN] [1509792184.371089]: Could not process inbound connection: [/amigo/rosbridge_websocket] is not a publisher of [/amigo/text_to_speech/input]. Topics are [['/rosout', 'rosgraph_msgs/Log']]{'message_definition': 'string data\n', 'callerid': '/amigo/text_to_speech', 'tcp_nodelay': '0', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'topic': '/amigo/text_to_speech/input', 'type': 'std_msgs/String'}
[WARN] [1509792192.373434]: Could not process inbound connection: [/amigo/rosbridge_websocket] is not a publisher of [/amigo/text_to_speech/input]. Topics are [['/rosout', 'rosgraph_msgs/Log']]{'message_definition': 'string data\n', 'callerid': '/amigo/text_to_speech', 'tcp_nodelay': '0', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'topic': '/amigo/text_to_speech/input', 'type': 'std_msgs/String'}

**Comment by Rayman** [comment]
How can I reproduce this?

**Comment by MaxBaeten** [comment]
What I did when I noticed this:

Killed amigo-start and started amigo-start debug:=true
Then open the amigo GUI and used the buttons of the arms. 

It might also occur without opening the amigo GUI and/or if you subscribe to journal ctl instead of starting amigo-start manually. I don't think this will occur without a real robot since you would have probably noticed this already.

**Comment by MaxBaeten** [comment]
I can't reproduce this error anymore. With journalctl or with a manual restart of amigo-start. If this comes back at any point I will reopen it again.
