### ISSUE TITLE
3D view jumps on pressing middle mouse button for panning

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_mobile_ui#7]
When trying to pan using the middle mouse button, the 3D view interface jumps to another position. Very annoying

**Comment by LFBFerreira** [comment]
![](http://cdn.alltheragefaces.com/img/faces/large/sad-i-know-that-feel-bro-l.png)

This only happens on some PCs, not all. Its annoying indeed, and i think several people looked at it but the fix only worked for some people. Also happens in mine in case someone wants to try a fix

**Comment by reinzor** [comment]
Fixed by 0c74108b9a425200f07dc1d1449d69f3816db6a2
