### ISSUE TITLE
client gets disconnected

### ISSUE THREAD

**Issue by robinsoetens** [tue-robotics/tue_mobile_ui#8]
Possibly because of new topic names after launch structure update. Error in astart:

===========

[INFO] [WallTime: 1425560023.041551] Client connected.  2 clients total.
[ERROR] [WallTime: 1425560023.096441] [Client 1] [id: call_service:/amigo/skill_server/get_api:1] call_service InvalidServiceException: Service /amigo/skill_server/get_api does not exist
[INFO] [WallTime: 1425560023.239707] [Client 1] Subscribed to /text_to_speech/input
[INFO] [WallTime: 1425560023.245607] [Client 1] Subscribed to /amigo/battery_percentage
[ERROR] [WallTime: 1425560025.096624] [Client 1] [id: call_service:/get_alive_nodes:4] call_service InvalidServiceException: Service /get_alive_nodes does not exist
[INFO] [WallTime: 1425560027.101798] Client disconnected. 1 clients total.

**Comment by Rayman** [comment]
Fixed by 2d577f95bb38847cc86e132dcd8858351f5faa15
