### ISSUE TITLE
Hardcoded topics

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_mobile_ui#9]
Removing /amigo/ from the topics works well, however, in case of the services, it seems that it doesn't work out-of-the-box...

**Comment by jlunenburg** [comment]
I'd rather call this a bug: the mobile ui does not work for SERGIO right now. Can't we fork rosbridge, fix the namespacing (getNamespace(), read the discussion ;) ) and send a pull request???

**Comment by Rayman** [comment]
Yeah that's a good idea. I'll look into this.

**Comment by Rayman** [comment]
This will be fixed by RobotWebTools/rosbridge_suite#178. In the meantime we'll use our forked version.
